version: '3.4'

services:
  debian_service:
    build:
      context: ./
      dockerfile: Dockerfile_debian_latest
    container_name: debian_latest_container
    tty: true

  ubuntu_service:
    build:
      context: ./
      dockerfile: Dockerfile_ubuntu_latest
    container_name: ubuntu_latest_container
    tty: true